import { Annotation } from "./Annotation";
import { Period } from "./Period";
import { CodeableConcept } from "./CodeableConcept";
import { Range } from "./Range";
import { Timing } from "./Timing";
import { Quantity } from "./Quantity";
import { DomainResource } from "./DomainResource";
import { Ratio } from "./Ratio";
import { Reference } from "./Reference";
import { Identifier } from "./Identifier";

export type ServiceRequest = DomainResource & {
    performerType?: CodeableConcept;
    category?: CodeableConcept[];
    insurance?: Reference[];
    instantiatesCanonical?: string[];
    instantiatesUri?: string[];
    relevantHistory?: Reference[];
    asNeeded?: boolean | CodeableConcept;
    supportingInfo?: Reference[];
    encounter?: Reference;
    patientInstruction?: string;
    specimen?: Reference[];
    reasonCode?: CodeableConcept[];
    authoredOn?: string;
    note?: Annotation[];
    requisition?: Identifier;
    locationReference?: Reference[];
    requester?: Reference;
    priority?: string;
    status: string;
    code?: CodeableConcept;
    identifier?: Identifier[];
    doNotPerform?: boolean;
    bodySite?: CodeableConcept[];
    intent: string;
    replaces?: Reference[];
    orderDetail?: CodeableConcept[];
    basedOn?: Reference[];
    quantity?: Ratio | Range | Quantity;
    locationCode?: CodeableConcept[];
    subject: Reference;
    occurrence?: Timing | Period | string;
    performer?: Reference[];
    reasonReference?: Reference[];
};