import { Annotation } from "./Annotation";
import { Attachment } from "./Attachment";
import { Period } from "./Period";
import { CodeableConcept } from "./CodeableConcept";
import { DomainResource } from "./DomainResource";
import { Reference } from "./Reference";
import { Identifier } from "./Identifier";

export type Media = DomainResource & {
    deviceName?: string;
    encounter?: Reference;
    content: Attachment;
    frames?: number;
    width?: number;
    reasonCode?: CodeableConcept[];
    type?: CodeableConcept;
    created?: Period | string;
    modality?: CodeableConcept;
    duration?: number;
    note?: Annotation[];
    status: string;
    identifier?: Identifier[];
    operator?: Reference;
    bodySite?: CodeableConcept;
    issued?: string;
    device?: Reference;
    basedOn?: Reference[];
    partOf?: Reference[];
    subject?: Reference;
    view?: CodeableConcept;
    height?: number;
};