name: Lint if snapshots change

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/lint.yaml"
      - "test/aidbox_sdk/snapshots/**"
      - "resources/sdk/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge TypeScript SDK files
        run: |
          cp -r -u resources/sdk/typescript/* test/aidbox_sdk/snapshots/typescript/

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: test/aidbox_sdk/snapshots/typescript/package-lock.json

      # - name: Cache Node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.npm
      #       **/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install system and client dependencies
        run: |
          sudo apt -y update && sudo apt install -y rlwrap
          npm ci

      - name: Run ESLint
        run: cd test/aidbox_sdk/snapshots/typescript && npm run lint
